apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-delivery.fullname" . }}-tracking-worker-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-delivery.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
data:
  PORT: {{ .Values.trackingWorker.env.PORT | quote }}
  METRICS_PORT: {{ .Values.trackingWorker.env.METRICS_PORT | quote }}
  ENVIRONMENT: {{ .Values.global.environment | quote }}
  SIMULATION_STEP_DELAY_SEC: {{ .Values.trackingWorker.env.SIMULATION_STEP_DELAY_SEC | quote }}
  NATS_URL: "nats://{{ include "kube-delivery.fullname" . }}-nats:4222"
  NATS_STREAM: "DELIVERY_EVENTS"
  NATS_SUBJECT: "delivery.shipments.created"
  NATS_CONSUMER_GROUP: "tracking-workers"
  MAX_RETRIES: "3"
  RETRY_BACKOFF_SEC: "1.0"
