{{- if and .Values.trackingWorker.enabled .Values.trackingWorker.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kube-delivery.fullname" . }}-tracking-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-delivery.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "kube-delivery.fullname" . }}-tracking-worker
  minReplicas: {{ .Values.trackingWorker.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.trackingWorker.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.trackingWorker.autoscaling.targetCPUUtilizationPercentage }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
{{- end }}
