apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-delivery.fullname" . }}-tracking-worker
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-delivery.labels" . | nindent 4 }}
    app.kubernetes.io/component: worker
spec:
  type: {{ .Values.trackingWorker.service.type }}
  ports:
    - name: health
      port: {{ .Values.trackingWorker.service.port }}
      targetPort: health
      protocol: TCP
    - name: metrics
      port: {{ .Values.trackingWorker.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "kube-delivery.trackingWorker.selectorLabels" . | nindent 4 }}
