apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-delivery.fullname" . }}-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-delivery.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - name: postgres
      port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    {{- include "kube-delivery.postgres.selectorLabels" . | nindent 4 }}
