apiVersion: v1
kind: Service
metadata:
  name: {{ include "kube-delivery.fullname" . }}-nats
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-delivery.labels" . | nindent 4 }}
    app.kubernetes.io/component: message-broker
spec:
  type: ClusterIP
  ports:
    - name: nats
      port: 4222
      targetPort: 4222
      protocol: TCP
    - name: monitor
      port: 8222
      targetPort: 8222
      protocol: TCP
  selector:
    {{- include "kube-delivery.nats.selectorLabels" . | nindent 4 }}
