apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-delivery-staging
  namespace: argocd
  labels:
    environment: staging
spec:
  project: default
  source:
    repoURL: https://github.com/AAAmer91/kube-delivery-platform.git
    targetRevision: HEAD
    path: deploy/helm/kube-delivery-platform
    helm:
      valueFiles:
        - values.yaml
        - values-staging.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
