apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-delivery-production
  namespace: argocd
  labels:
    environment: production
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    repoURL: https://github.com/AAAmer91/kube-delivery-platform.git
    targetRevision: main
    path: deploy/helm/kube-delivery-platform
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    # Manual / Protected Sync for Production
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        platform.kube-delivery.io/security-profile: restricted
        pod-security.kubernetes.io/enforce: restricted
        pod-security.kubernetes.io/enforce-version: latest
