apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-delivery-production
  namespace: argocd
  labels:
    environment: production
spec:
  project: default
  source:
    repoURL: https://github.com/AAAmer91/kube-delivery-platform.git
    targetRevision: HEAD
    path: deploy/helm/kube-delivery-platform
    helm:
      valueFiles:
        - values.yaml
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    # Manual / Protected Sync for Production
    syncOptions:
      - CreateNamespace=true
