{{- if and .Values.networkPolicy.enabled .Values.postgres.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "kube-delivery.fullname" . }}-allow-postgres
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-delivery.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgres
  policyTypes:
    - Ingress
  ingress:
    # Allow 5432 ingress ONLY from API, Worker, and Migration Job within namespace
    - from:
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: shipment-api
        - podSelector:
            matchLabels:
              app.kubernetes.io/name: tracking-worker
        - podSelector:
            matchLabels:
              app.kubernetes.io/component: migration-job
      ports:
        - protocol: TCP
          port: 5432
{{- end }}
