global:
  environment: preview
  domain: preview.delivery.local

shipmentApi:
  replicaCount: 1
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi

trackingWorker:
  replicaCount: 1
  autoscaling:
    enabled: false
  resources:
    requests:
      cpu: 20m
      memory: 64Mi
    limits:
      cpu: 150m
      memory: 128Mi

postgres:
  persistence:
    enabled: false # Ephemeral emptyDir in PR clusters for high speed
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 200m
      memory: 256Mi

nats:
  jetstream:
    fileStorage:
      size: 512Mi
  resources:
    requests:
      cpu: 20m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 128Mi

resourceQuota:
  hard:
    pods: "10"
    requests.cpu: "1"
    requests.memory: 1Gi
    limits.cpu: "2"
    limits.memory: 2Gi
