apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-drop-all-capabilities
  annotations:
    policies.kyverno.io/title: Drop All Capabilities
    policies.kyverno.io/category: Pod Security Standards (Restricted)
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Containers must drop all default Linux capabilities to enforce least privilege.
spec:
  validationFailureAction: Enforce
  background: true
  rules:
    - name: drop-all
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaceSelector:
                matchLabels:
                  platform.kube-delivery.io/security-profile: restricted
      validate:
        message: "Containers must drop ALL capabilities (securityContext.capabilities.drop=['ALL'])."
        foreach:
          - list: request.object.spec.[ephemeralContainers, initContainers, containers][]
            pattern:
              securityContext:
                capabilities:
                  drop:
                    - ALL
