apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kube-delivery.fullname" . }}-shipment-api-config
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-delivery.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
data:
  PORT: {{ .Values.shipmentApi.env.PORT | quote }}
  LOG_LEVEL: {{ .Values.shipmentApi.env.LOG_LEVEL | quote }}
  ENVIRONMENT: {{ .Values.global.environment | quote }}
  SHUTDOWN_TIMEOUT_SECONDS: {{ .Values.shipmentApi.env.SHUTDOWN_TIMEOUT_SECONDS | quote }}
  NATS_URL: "nats://{{ include "kube-delivery.fullname" . }}-nats:4222"
  NATS_STREAM: "DELIVERY_EVENTS"
  NATS_SUBJECT: "delivery.shipments.created"
