{{- if and .Values.shipmentApi.enabled .Values.shipmentApi.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "kube-delivery.fullname" . }}-shipment-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-delivery.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  scaleTargetRef:
    {{- if .Values.shipmentApi.argoRollouts.enabled }}
    apiVersion: argoproj.io/v1alpha1
    kind: Rollout
    {{- else }}
    apiVersion: apps/v1
    kind: Deployment
    {{- end }}
    name: {{ include "kube-delivery.fullname" . }}-shipment-api
  minReplicas: {{ .Values.shipmentApi.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.shipmentApi.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.shipmentApi.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.shipmentApi.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.shipmentApi.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.shipmentApi.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
        - type: Percent
          value: 100
          periodSeconds: 15
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
        - type: Percent
          value: 10
          periodSeconds: 60
{{- end }}
