{{- if and .Values.shipmentApi.enabled .Values.shipmentApi.argoRollouts.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "kube-delivery.fullname" . }}-shipment-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kube-delivery.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
spec:
  {{- if not .Values.shipmentApi.autoscaling.enabled }}
  replicas: {{ .Values.shipmentApi.replicaCount }}
  {{- end }}
  strategy:
    canary:
      canaryService: {{ include "kube-delivery.fullname" . }}-shipment-api-canary
      stableService: {{ include "kube-delivery.fullname" . }}-shipment-api-stable
      analysis:
        templates:
          - templateName: {{ include "kube-delivery.fullname" . }}-shipment-api-analysis
        args:
          - name: service-name
            value: {{ include "kube-delivery.fullname" . }}-shipment-api
      steps:
        - setWeight: 10
        - pause: { duration: 30s }
        - setWeight: 25
        - pause: { duration: 30s }
        - setWeight: 50
        - pause: { duration: 30s }
        - setWeight: 100
  selector:
    matchLabels:
      {{- include "kube-delivery.shipmentApi.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "kube-delivery.shipmentApi.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/part-of: kube-delivery-platform
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/metrics"
    spec:
      serviceAccountName: {{ include "kube-delivery.fullname" . }}-shipment-api
      terminationGracePeriodSeconds: 30
      {{- with .Values.securityDefaults.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shipmentApi.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.shipmentApi.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: shipment-api
          image: {{ include "kube-delivery.shipmentApi.image" . | quote }}
          imagePullPolicy: {{ .Values.shipmentApi.image.pullPolicy }}
          {{- with .Values.securityDefaults.containerSecurityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          envFrom:
            - configMapRef:
                name: {{ include "kube-delivery.fullname" . }}-shipment-api-config
            - secretRef:
                name: {{ .Values.postgres.auth.existingSecret | quote }}
          {{- with .Values.shipmentApi.probes.startup }}
          startupProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.shipmentApi.probes.liveness }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.shipmentApi.probes.readiness }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          resources:
            {{- toYaml .Values.shipmentApi.resources | nindent 12 }}
          volumeMounts:
            - name: tmp-scratch
              mountPath: /tmp
      volumes:
        - name: tmp-scratch
          emptyDir:
            medium: Memory
            sizeLimit: 64Mi
{{- end }}
